// <auto-generated />
namespace FashionPlatform.Domain.Migrations.MigrationProduct
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DeletTestPropfromProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletTestPropfromProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201803122122076_DeletTestPropfromProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
